name: Test CI
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/test.yml'
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rokibhasansagar/img2avifenc:latest
      volumes:
        - tmp:/data
    steps:
      - name: Check
        run: |
          command -v avifenc || true
          avifenc --help
          # sudo pacman -Sy --noconfirm --needed tree
      - name: Run
        run: |
          set -x
          cd /data
          curl -sL "https://github.blog/wp-content/uploads/2025/12/527215072-2cd64986-d18e-4a0f-a6f6-fbac2b4d7555.jpg?w=1536" -o input.jpg && echo
          for qual in 36 45 50 60; do
            avifenc -q ${qual} --speed 0 --codec ${codec:-aom} --depth 12 --cicp 1/13/1 -a sb-size=64 -a tune=iq --output output_q${qual}.avif input.jpg 1>/dev/null
            curl -s -F "file=@output_q${qual}.avif" https://temp.sh/upload && echo
          done
          ls -lAog /data
          md5sum /data/*.avif
  

